/*
 * CalculateElectricBill.java
 *
 * Created on June 18, 2003, 12:04 PM
 */


import javax.swing.JOptionPane;

/**
 *
 * @author  Susan Williams
 * @version
 */
public class CalculateElectricBill extends javax.swing.JFrame {

    /** Creates new form CalculateElectricBill */
    public CalculateElectricBill() {
        initComponents ();
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        startLabel = new javax.swing.JLabel();
        meterStartText = new javax.swing.JTextField();
        endLabel = new javax.swing.JLabel();
        meterEndText = new javax.swing.JTextField();
        amtDueLabel = new javax.swing.JLabel();
        amtDueText = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));
        setTitle("Calculate Electric Bill");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );

        startLabel.setText("Starting Meter Reading");
        startLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        getContentPane().add(startLabel);



        getContentPane().add(meterStartText);


        endLabel.setText("Ending Meter Reading");
        endLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        getContentPane().add(endLabel);


        meterEndText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterEndTextActionPerformed(evt);
            }
        }
        );

        getContentPane().add(meterEndText);


        amtDueLabel.setText("Amount Due");
        amtDueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        getContentPane().add(amtDueLabel);


        amtDueText.setEditable(false);

        getContentPane().add(amtDueText);


        nextButton.setText("Next Reading");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        }
        );

        getContentPane().add(nextButton);


        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        }
        );

        getContentPane().add(closeButton);

    }//GEN-END:initComponents

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
// Add your handling code here:
      System.exit(0);
  }//GEN-LAST:event_closeButtonActionPerformed

  private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
// Add your handling code here:
      meterStartText.setText("");
      meterEndText.setText("");
      amtDueText.setText("");
      meterStartText.requestFocus();
  }//GEN-LAST:event_nextButtonActionPerformed

  private void meterEndTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterEndTextActionPerformed
// Add your handling code here:
      endReading = Integer.parseInt(meterEndText.getText());
      startReading = Integer.parseInt(meterStartText.getText());

      kwhUsed = endReading - startReading;
      amtDue = kwhUsed * .5;

      amtDueText.setText("" + amtDue);

  }//GEN-LAST:event_meterEndTextActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new CalculateElectricBill ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel startLabel;
    private javax.swing.JTextField meterStartText;
    private javax.swing.JLabel endLabel;
    private javax.swing.JTextField meterEndText;
    private javax.swing.JLabel amtDueLabel;
    private javax.swing.JTextField amtDueText;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
    private int startReading, endReading, kwhUsed;
    private double amtDue;

}
